name: Trigger Deploy (Frontend)

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Запускаем деплой в nsinvest-deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/lantemir/nsinvest-deploy/dispatches \
            -d '{"event_type": "deploy_triggered_from_frontend"}'